hello_world:
  image: alpine:latest
  script:
    - date
    - echo "hello world, in the default 'test' stage"
    - if [ -z "$TEST" ]; then echo '$TEST is empty'; fi
    - if [ -z "$TEST2" ]; then echo '$TEST2 is empty'; fi
    - echo "$TEST and see if the result is masked"
    - echo "$TEST2 and see if the result is masked"
